# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('current_status', models.CharField(max_length=5)),
                ('prev_status', models.CharField(max_length=5)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
