# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='pid',
            field=models.TextField(),
        ),
    ]
