# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160514_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='current_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='services',
            name='prev_status',
            field=models.CharField(max_length=15),
        ),
    ]
