# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160507_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='last_up_time',
            new_name='last_updated_time',
        ),
    ]
